### ISSUE TITLE
Crashing on Android 8+

### ISSUE THREAD

**Issue by qsdamar** [leandrosimoes/react-native-android-notification-listener#1]
I'm stuck for few days with this issue. On Android 8+ app keeps crashing, I think it's caused due to background restrictions for 8+, because I tested on Android lower than 8 and it works perfect. 

I'm trying with some react native background libraries, but doesn't help. Obviously the library has to be modified, but my Java knowledge is limited.

Hope that someone can help. Thanks.

**Comment by leandrosimoes** [comment]
Hi @qsdamar, I'll test with Android 9 asap, but in the meantime, could you please provide some adb log to see if we can find why it is crashing? I don't know if you are familiar with the adb, but the command to get error logs is: `adb logcat *:E` for errors only or `adb logcat *:F` for fatals only. You can check the adb docs here: https://developer.android.com/studio/command-line/logcat#filteringOutput

Post here on comments the log asap so I can help to analyze too.

**Comment by qsdamar** [comment]
Hi @leandrosimoes, thank you for quick response. I have tested on Android 9 and this is adb log for *:E:

11-24 19:59:45.664 18054 18054 E AndroidRuntime: FATAL EXCEPTION: main
11-24 19:59:45.664 18054 18054 E AndroidRuntime: Process: com.testnotif, PID: 18054
11-24 19:59:45.664 18054 18054 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.react.bridge.JavaScriptModule com.facebook.react.bridge.ReactApplicationContext.getJSModule(java.lang.Class)' on a null object reference
11-24 19:59:45.664 18054 18054 E AndroidRuntime:        at com.lesimoes.androidnotificationlistener.RNAndroidNotificationListenerModule.sendEvent(RNAndroidNotificationListenerModule.java:60)
11-24 19:59:45.664 18054 18054 E AndroidRuntime:        at com.lesimoes.androidnotificationlistener.RNAndroidNotificationListener.onNotificationPosted(RNAndroidNotificationListener.java:33)
11-24 19:59:45.664 18054 18054 E AndroidRuntime:        at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:338)
11-24 19:59:45.664 18054 18054 E AndroidRuntime:        at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2022)
11-24 19:59:45.664 18054 18054 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
11-24 19:59:45.664 18054 18054 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:216)
11-24 19:59:45.664 18054 18054 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7266)
11-24 19:59:45.664 18054 18054 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-24 19:59:45.664 18054 18054 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
11-24 19:59:45.664 18054 18054 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
11-24 19:59:46.436 17517 17517 E msgr.ForegroundServiceTracker: startForegroundService: com.facebook.messaging.chatheads.service.ChatHeadService
11-24 19:59:47.517  3003  3389 E installd: Failed to free up 1048576000 on /data; final free space 776974336: Success
11-24 19:59:47.564  3003  3389 E installd: Failed to free up 1048576000 on /data; final free space 776974336: Success
11-24 19:59:50.840  3292  3699 E Watchdog: !@Sync 11373 [2019-11-24 19:59:50.840] FD count : 708
11-24 19:59:52.285  2852  2988 E BufferQueueProducer: [[17517]#4] disconnect: not connected (req=1)
11-24 19:59:52.289  3292  8751 E WindowManager: win=Window{d67cb8e u0 com.facebook.orca} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.WindowManagerService.tryStartExitingAnimation:2769 com.android.server.wm.WindowManagerService.relayoutWindow:2466 com.android.server.wm.Session.relayoutForTranslate:308 android.view.IWindowSession$Stub.onTransact:518 com.android.server.wm.Session.onTransact:192 android.os.Binder.execTransact:739 <bottom of call stack>

Fatal errors list was empty. App name is com.testnotif.
This is happening when app is in the background, and I am also getting battery warning. 
Again, this only happens on Android 8+.

**Comment by leandrosimoes** [comment]
Thanks @qsdamar , I'll take a look and let you know asap.

**Comment by leandrosimoes** [comment]
Hi @qsdamar, I couldn't simulate the error here, but doing some researches, I think that maybe this fatal error has been caused because the reactContext is null when calling some of the functions. So, I did some verifications about the reactContext being null. Could you please help me to test this? Just install the package from Github's repository to see if the error stops before I release a new version?

**Comment by qsdamar** [comment]
HI @leandrosimoes, I have tested a new version and it is still crashing when the app is in the background. On my device, app crashes after going in background. Not immediately, but after one or few hours. Can you please leave the app installed with permission granted for few hours on your device, so we can know if it will crash? Thanks.

**Comment by leandrosimoes** [comment]
Hi @qsdamar, sorry about that. I'll do what you said about install and wait a few hours to see what I get and let you know asap. Thanks for the advice.

**Comment by leandrosimoes** [comment]
Hi @qsdamar, how are you? I did some fixes in the code and push them to master. Could you please install the package using the last modifications in this repo and see if the error stops? Thanks a lot!

**Comment by qsdamar** [comment]
Hi @leandrosimoes, I have installed the latest modifications and I'm waiting now. I will let you now the results tommorow. Thank you!

**Comment by leandrosimoes** [comment]
Hi @qsdamar, how are you? Any news about the error?

**Comment by qsdamar** [comment]
Hi @leandrosimoes, my apologies for late response. I'm a bit busy these days, but I still need this library to work. I have tested the latest version and this time it took about 12 hours to crash. But I did a little research, do you think that this library needs something like foreground service? I found the code for one similar listener and it includes something like this. I'll paste the code below: 

`@Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        this.handler.post(this.runnableCode); // Starting the interval
        // Turning into a foreground service
        Intent notificationIntent = new Intent(this, MainActivity.class);
        PendingIntent contentIntent = PendingIntent.getActivity(this, 0, notificationIntent, PendingIntent.FLAG_CANCEL_CURRENT);
        Notification notification = new NotificationCompat.Builder(this, CHANNEL_ID)
                .setContentTitle("Heartbeat service")
                .setContentText("Running...")
                .setSmallIcon(R.mipmap.ic_launcher)
                .setContentIntent(contentIntent)
                .setOngoing(true)
                .build();
        startForeground(SERVICE_NOTIFICATION_ID, notification);
        return START_STICKY;
    }`

My Java knowledge is limited, but maybe the notification has to appear all the time in the status bar to make this work? What do you think about that? Thanks a lot!

**Comment by leandrosimoes** [comment]
Hi @qsdamar, no problem! Well, my knowledge in Java is not that good too haha. But thanks that, I will take a look at the article and do some researches to see what I can find about the foreground service and try to implement if it is the case. In the meantime, I have my application installed in my Mi A2, with Android 9, and the app didn't crash anymore after the last modifications that I made. Do you know if your app crash when a specific type of notification is presented? For example, in my case, the application was crashing because of the notification that is presented when you are listening to a Whatsapp audio. The one with an audio control to play, pause the audio.

**Comment by qsdamar** [comment]
Hi @leandrosimoes, I am testing on Samsung J5 2017 with Android 9, but I will keep tracking crashes, maybe it could be some special notification that makes app to crash. If I figure out something, I will let you know. In the meantime, if you are able, please do some research about foreground services and notification that appear constantly in status bar when the the service is running, because I think it's kind of related to background restrictions that are introduced in Android 8+. Thank you so much!

**Comment by leandrosimoes** [comment]
Sorry, @qsdamar, I'm very busy these days, I'll take a look at that asap tho.

**Comment by trytony** [comment]
On android 9, there was also a crash.

**Comment by qsdamar** [comment]
HI @leandrosimoes, I have tested your latest version and it's working perfectly for a whole day. Just one note for your library, there are 2 syntax errors, missing ; on two lines. I took screenshot of the code so you can easily fix it. 

https://imgur.com/a/JnkQGIB

Please fix that and push again, it's not needed to touch anything else. Thank you so much!

**Comment by leandrosimoes** [comment]
Hi @qsdamar, great to hear that! I'll create a new release in a minute. Thanks a lot!

**Comment by leandrosimoes** [comment]
Done @qsdamar, thanks again for the help!

**Comment by leandrosimoes** [comment]
Issue fixed in the release [v1.0.4](https://github.com/leandrosimoes/react-native-android-notification-listener/releases/tag/v1.0.4)
