### ISSUE TITLE
✨ [FEATURE] Retrieve app icon and Images from Notifications

### ISSUE THREAD

**Issue by arunahuja94** [leandrosimoes/react-native-android-notification-listener#10]
**Is your feature request related to a problem? Please describe.**
I am trying to retrieve app icon and images from notification

**Describe the solution you'd like**

**Changes I made in RNAndroidNotificationListener.java ->**

`import android.content.pm.PackageManager;
import android.graphics.Bitmap;     
import java.io.ByteArrayOutputStream;`

        int id1 = notification.extras.getInt(Notification.EXTRA_SMALL_ICON);  
	PackageManager manager = getPackageManager();
	** Resources resources = manager.getResourcesForApplication(app); ** // Getting error in this 
	// Drawable icon = resources.getDrawable(id1); 

         
  **Bitmap id = notification.largeIcon;  //Not able to receive Large image**  

	if(id != null) {  
            ByteArrayOutputStream stream = new ByteArrayOutputStream();  
            id.compress(Bitmap.CompressFormat.PNG, 100, stream);  
            byte[] byteArray = stream.toByteArray();  
            serviceIntent.putExtra("icon",byteArray);  
        } 

**Tried This also**

       if (notification.extras.containsKey(Notification.EXTRA_PICTURE)) {
            // this bitmap contain the picture attachment
            Bitmap bmp = (Bitmap) notification.extras.get(Notification.EXTRA_PICTURE);
	    serviceIntent.putExtra("bmp", bmp);
        }

**Additional context**
Can You please help me with this @leandrosimoes

**Comment by leandrosimoes** [comment]
Hi @arunahuja94! What a coincidence! I was looking for more info about how to do that a few hours ago. I think that is a way, I'll try to implement and test it later and let you know asap. Thanks again.

**Comment by arunahuja94** [comment]
Hi @leandrosimoes ,
found any more info regarding this?

**Comment by leandrosimoes** [comment]
Hi @leandrosimoes 
I did some experiments but nothing successfully yet. I'll try other things tomorrow and let you know.

**Comment by leandrosimoes** [comment]
Hi @arunahuja94 I just made some changes and I think that now the icon and image are working, I'll just do more tests and let you know.

**Comment by arunahuja94** [comment]
@leandrosimoes that's awesome, thanks

**Comment by leandrosimoes** [comment]
@arunahuja94 I just pushed my changes to this new branch [feature/notification-icon-and-image](https://github.com/leandrosimoes/react-native-android-notification-listener/tree/feature/notification-icon-and-image). 

Could you please check out it and test it to see if everything works fine. I did some tests here and everything seems fine but will be nice if you test too just to be sure.

**Comment by arunahuja94** [comment]
Hi @leandrosimoes ,

Will test it and let you Know asap

**Comment by arunahuja94** [comment]
Hi @leandrosimoes 

**Was able to retrieve the icon**

But no luck with image as you can see in the Screenshot below that I got the image in the notification 

![image](https://user-images.githubusercontent.com/78036151/106620294-70b04780-6597-11eb-8e17-03120c062aa1.png)

But not using notification listener

![icon_retrieved](https://user-images.githubusercontent.com/78036151/106619599-c3d5ca80-6596-11eb-89ae-69d9445bede5.png)

and can you please share the list of apps that you tested for the image

**Comment by leandrosimoes** [comment]
Hi, @arunahuja94 I'm really struggling with that. I can't make it work on Telegram and I can't find anything on the internet that helps.

I tested in two apps, one personal and [this one](https://play.google.com/store/apps/details?id=com.wagner.valentin.notificationmaker2&hl=en&gl=US) and it works for both.

Seem that the problem with the Telegram is that the type of notification is called "Stacked" and I can't find how to get the image from it.

**Comment by leandrosimoes** [comment]
Hi, @arunahuja94 I'm closing this issue because part of the problem was solved and open another issue https://github.com/leandrosimoes/react-native-android-notification-listener/issues/15 as a BUG to try to fix this problem with Telegram and other apps that use this Stack kind of notifications. Any updates you can send directly there now.

I just released the v3.1.0 of the npm package with the modifications that were already made too. You can check [here](https://github.com/leandrosimoes/react-native-android-notification-listener/releases/tag/v3.1.0).

Thanks.
