### ISSUE TITLE
🐛 [BUG] json Parse Issue 

### ISSUE THREAD

**Issue by arunahuja94** [leandrosimoes/react-native-android-notification-listener#13]
**Describe the bug**
Json Parse Issue in sample/App.js 
`setLastNotification(JSON.parse(lastStoredNotification))` 

**Screenshots**
![before_change](https://user-images.githubusercontent.com/78036151/106397725-cf10e500-6434-11eb-9486-5e6ff433cb28.png)

**Library version (please complete the following information):**
 - Version [e.g. v3.0.0]

**Smartphone (please complete the following information):**
 - Device: Android Simulator
 - OS: Pixel_4_api_29

**Additional context**
Was Able to make it work by doing Json parse twice in app.js 
`setLastNotification(JSON.parse(JSON.parse(lastStoredNotification)))` 

![after_change](https://user-images.githubusercontent.com/78036151/106397634-74778900-6434-11eb-94d1-7f7191105868.png)

**Comment by leandrosimoes** [comment]
Hi @arunahuja94, here I just test it and everything works fine. Maybe you missed the changes in the documentation that said to handle the incoming notifications like this

```javascript
const headlessNotificationListener = async ({ notification }) => {}
```

and not like this anymore:

```javascript
const headlessNotificationListener = async (notification) => {
```

Check if this is the problem and let me know.

**Comment by leandrosimoes** [comment]
@arunahuja94 Another thing that can be wrong is that you do not need to `JSON.stringify` your incoming notification to store it in the `AsyncStorage` since the notification already is a JSON string.

**Comment by arunahuja94** [comment]
@leandrosimoes 
`const headlessNotificationListener = async ({ notification })  => {
    if (notification) {
        await AsyncStorage.setItem('@lastNotification', JSON.stringify(notification))
    }
}`

Made all the changes as per the documentation

**Comment by leandrosimoes** [comment]
> @leandrosimoes 
> `const headlessNotificationListener = async ({ notification })  => {
>     if (notification) {
>         await AsyncStorage.setItem('@lastNotification', JSON.stringify(notification))
>     }
> }`
> 
> Made all the changes as per the documentation

Here you are doing `JOSN.stringify` to store the notification, there's no need anymore because the notification received ia already a JSON string. Try to store without doing that.

**Comment by arunahuja94** [comment]
@leandrosimoes Thanks, Working Fine Now 
Forgot to change that
