### ISSUE TITLE
🐛 [BUG] Images from stack notifications are not being retrieved

### ISSUE THREAD

**Issue by leandrosimoes** [leandrosimoes/react-native-android-notification-listener#15]
**Describe the bug**
Some applications send their images in notifications called Stack Notifications. The `image` payload is not being retrieved by the module.

**To Reproduce**
1. Execute the `sample` application
2. Enable all permissions
3. Send an image in Telegram from another device so you can receive a notification
4. The `image` payload will be empty

**Expected behavior**
The `image` payload may have the image sent by Telegram as a base64 string

**Screenshots**
None

**Library version (please complete the following information):**
 - Version v3.0.0 and v3.1.0

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2
 - OS: Android 10
 - 
**Additional context**
More info on this closed issue: https://github.com/leandrosimoes/react-native-android-notification-listener/issues/10

**Comment by arunahuja94** [comment]
Hi @leandrosimoes 

I think its not possible to retrieve images from WhatsApp notification, after researching I found most of the apps that are doing that are using **FileObserver**  in the whatsapp images directory and whenever the new image is added in that directory , they access image from that directory

**Comment by Aakashsajjad095** [comment]
hi @leandrosimoes in new update groupedMessages array is empty all the time

**Comment by leandrosimoes** [comment]
Hi @arunahuja94 ... unfortunately I think that there's no way to retrieve the image from this kind of notification. I'll keep this issue open for now, just in case.

**Comment by leandrosimoes** [comment]
Hi @Aakashsajjad095 this is another issue, please, open a new issue with your problem so we can check it out.
