### ISSUE TITLE
🐛 [BUG] GroupedMessages array is empty

### ISSUE THREAD

**Issue by arunahuja94** [leandrosimoes/react-native-android-notification-listener#18]
**Describe the bug**
GroupedMessages array is empty all the time

**Screenshots**
![gm](https://user-images.githubusercontent.com/78036151/107880862-739c2800-6f07-11eb-9f66-612b41cff194.png)

**Library version (please complete the following information):**
 - Version [v3.1.0]

**Smartphone (please complete the following information):**
 - Device: [pixel_api_29 Android Emulator]
 - OS: [Android 10]

**Additional context**

Hi @leandrosimoes  , I was able to retrieve notification in this file `RNGroupedNotification.java`  checked using the **log.d** as shown in the snippet bellow 

`if (endIndex != -1) {`
            `Log.d("RNAndroidNotificationListener",formatedMessage.toString());`
            `this.title = formatedMessage.substring(0, endIndex).trim();`
            `this.text = formatedMessage.substring(endIndex + 1).trim();`
       ` } else {`
           `this.text = formatedMessage;`
        `}`

Testing further , will let you know if I found anything else

**Comment by Aakashsajjad095** [comment]
New version only tell about the totall number of notification? not about the complete message like perevious version?

**Comment by arunahuja94** [comment]
hi @Aakashsajjad095 

We are able to receive complete message like in previous version from all the apps , but in the case of apps like telegram, WhatsApp they provide stack/grouped notifications, so when we get notifications from more than one user from those apps , they tend to stack those notification, so we are providing those notifications in groupedMessages array, rest is working like before and groupedMessages issue will be resolved soon

**Comment by arunahuja94** [comment]
hi @leandrosimoes 

I think we should display notifications in case of grouped messages with something like as shown in screenshot below rather than hiding single notification in case of groupedMessages as per this

  `<View style={styles.notificationsWrapper}>`
  `{lastNotification && !hasGroupedMessages && <Notification {...lastNotification} />}`
   `{lastNotification && hasGroupedMessages && (`
   `<FlatList`
    `data={lastNotification.groupedMessages}`
     `keyExtractor={(_, index) => index.toString()}`
     `renderItem={({ item }) => (`
     `<Notification app={lastNotification.app} {...item} />`
      ` )}`
       ` />`
      ` )}`
       ` </View>`

**Screenshot**
![allNotif](https://user-images.githubusercontent.com/78036151/107888261-2f258200-6f31-11eb-865b-e286f59f91ac.png)


This will give us better understanding of what's goin on

**Comment by leandrosimoes** [comment]
Fixed in [v3.1.1](https://github.com/leandrosimoes/react-native-android-notification-listener/releases/tag/v3.1.1)

**Comment by arunahuja94** [comment]
Hi @leandrosimoes 

Please update **README.md** file

npm **_intall_** react-native-android-notification-listener
