### ISSUE TITLE
Cannot run in RN version 0.57.8

### ISSUE THREAD

**Issue by trytony** [leandrosimoes/react-native-android-notification-listener#2]
Hi, I tried to run in RN 0.57.8, but it doesn't seem to be supported.

**Comment by leandrosimoes** [comment]
Hi @trytony! I'll try to simulate this issue but in the meantime, could you please try to get more information about the error? Some compilation message, stack trace?
Information about the device like brand, Android version? With more information is ease to figure out what is going on. Thanks.

**Comment by leandrosimoes** [comment]
Hi @trytony, I tested here and it works. Could you please give me more information about the error, please? Some compilation message, stack trace? Information about the device like brand, Android version?

**Comment by leandrosimoes** [comment]
Closing: No enough information.
