### ISSUE TITLE
✨ How to get album art?

### ISSUE THREAD

**Issue by eticaretmuhendisi** [leandrosimoes/react-native-android-notification-listener#21]
Hello there,
First of all thank you for this beautiful package.
I want to get the album art of the song that is playing, can such a feature be added?

Example screenshots

![image](https://user-images.githubusercontent.com/35329314/119973196-dcda0f80-bfbb-11eb-9d37-e0e1b828b983.png)

![image](https://user-images.githubusercontent.com/35329314/119973564-4e19c280-bfbc-11eb-97e5-47ea904359a6.png)

**Comment by arunahuja94** [comment]
Hi @eticaretmuhendisi 

Album art feature will be added soon, once @leandrosimoes  reviews and merge the PR #22 

Thanks

**Comment by leandrosimoes** [comment]
Hi @eticaretmuhendisi 

Thanks to @arunahuja94 the support for the `largeIcon` property was added and you can now get the album art.

Thanks for submitting this issue and thanks again to @arunahuja94 for the PR.

**Comment by leandrosimoes** [comment]
Released in https://github.com/leandrosimoes/react-native-android-notification-listener/releases/tag/v3.1.2

**Comment by eticaretmuhendisi** [comment]
Wonderful, thanks you so match.
@arunahuja94  @leandrosimoes
