### ISSUE TITLE
Unexpected identifier

### ISSUE THREAD

**Issue by hungth84** [leandrosimoes/react-native-android-notification-listener#39]
I download the example to run and get error on android 5.1
![z3356174458133_298b32e77cc9d1c585ac491764e8aaee](https://user-images.githubusercontent.com/16811019/164291869-e5124e3d-4003-4c6c-8001-65b4246b43c7.jpg)

**Comment by leandrosimoes** [comment]
This issue is being closed because do not contains enough information. Please, open a new issue using the bug template and provide all the required information.
