### ISSUE TITLE
🐞 [BUG] A problem occurred evaluating & configuring project ':react-native-android-notification-listener'.

### ISSUE THREAD

**Issue by ChineseOuchie** [leandrosimoes/react-native-android-notification-listener#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npx react-native run-android` will crash when trying to compile/build react-native-android-notification-listener

React 17.0.2
React-native 0.68.1
react-native-android-notification-listener ^4.0.2

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '\node_modules\react-native-android-notification-listener\android\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':react-native-android-notification-listener'.     
> multiple points
```

```
2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-android-notification-listener'.    
> compileSdkVersion is not specified. Please add it to build.gradle
```

### Expected Behavior

To compile without crashing.

### Steps To Reproduce

1. npx react-native init <project_name>
2. cd <project_name>
3. npm install react-native-android-notification-listener
4. npx react-native run-android

### Library version that you are testing

4.0.2

### Device

Android Emulator

### Android Version

Android 11

**Comment by ChineseOuchie** [comment]
It seems to be working now. Changed nothing, but I have another problem. I can't request "permissions"

After pressing the request permission button I get: `TypeError: Cannot read properties of undefined (reading 'requestPermission')`

```
const handleOnPressPermissionButton = async () => {
    try {
      RNAndroidNotificationListener.requestPermission()

    } catch(e) {
      console.log(e)
    }
  }
```

**Comment by leandrosimoes** [comment]
Hi @ChineseOuchie. 

Maybe is still something related to the compileSdkVersion problem. What did you do to fix the problem?

**Comment by ChineseOuchie** [comment]
I use `npx react-native start` instead of `npx react-native run-android`
