### ISSUE TITLE
🐞Stops Listening

### ISSUE THREAD

**Issue by mtalhagaoglu** [leandrosimoes/react-native-android-notification-listener#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every time I exit from the application, I need to disable&enable the permission to listen to notifications. App already has the approval for the listening notification but does not listen.

### Expected Behavior

It shall listen to the notification if it has approval.

### Steps To Reproduce

1. Request Notification Listen to Permission
2. Approve the permission
3. Kill the app
4. Open App
5. Does not listen notification

### Library version that you are testing

v4.1.0

### Device

Xiaomi Redmi 9T

### Android Version

Android 11

**Comment by leandrosimoes** [comment]
Fixed on [v5.0.0](https://github.com/leandrosimoes/react-native-android-notification-listener/releases/tag/v5.0.0)
