### ISSUE TITLE
🐞 [BUG] <Can't build a freshly initializated project>

### ISSUE THREAD

**Issue by retr00h** [leandrosimoes/react-native-android-notification-listener#44]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

After installing and importing this library the project doesn't build and I'm getting this error:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\NotificationManager\node_modules\react-native-android-notification-listener\android\build.gradle' line: 106

* What went wrong:
A problem occurred configuring project ':react-native-android-notification-listener'.
> Could not resolve all files for configuration ':react-native-android-notification-listener:implementation'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :react-native-android-notification-listener
      > Cannot choose between the following variants of com.facebook.react:react-native:0.69.0:
          - debugVariantDefaultRuntimePublication
          - releaseVariantDefaultRuntimePublication
        All of them match the consumer attributes:
          - Variant 'debugVariantDefaultRuntimePublication' capability com.facebook.react:react-native:0.69.0:
              - Unmatched attributes:
                  - Provides com.android.build.api.attributes.BuildTypeAttr 'debug' but the consumer didn't ask for it
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.dependency.bundling 'external' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'aar' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
          - Variant 'releaseVariantDefaultRuntimePublication' capability com.facebook.react:react-native:0.69.0:
              - Unmatched attributes:
                  - Provides com.android.build.api.attributes.BuildTypeAttr 'release' but the consumer didn't ask for it
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.dependency.bundling 'external' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'aar' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it

### Expected Behavior

I'd expect the app to build and execute (on Android)

### Steps To Reproduce

Assuming that a developement environment is correctly set up:
1. run `npx react-native init ProjectNameHere` (as per [RN documentation](https://reactnative.dev/docs/environment-setup))
2. (optionally) run `npx react-native run-android`
3. add the following line to `index.js`
`AppRegistry.registerHeadlessTask(RNAndroidNotificationListenerHeadlessJsName,	() => headlessNotificationListener)`
4. add the following lines to `App.js`
`import { AppRegistry } from 'react-native'`
`import RNAndroidNotificationListener, { RNAndroidNotificationListenerHeadlessJsName } from 'react-native-android-notification-listener'`
6. run `npx react-native run-android`

### Library version that you are testing

v4.1.0

### Device

Android Virtual Device (Pixel 4)

### Android Version

11

**Comment by leandrosimoes** [comment]
Fixed on [Release v5.0.0](https://github.com/leandrosimoes/react-native-android-notification-listener/releases/tag/v5.0.0)

**Comment by Vlad-Karlin** [comment]
Hey, 

Could you please elaborate on how this bug was fixed? The release link contains 55 changed files with 2,875 additions and 3,662 deletions. 

Any hints would be highly appreciated :)

**Comment by leandrosimoes** [comment]
> Hey,
> 
> Could you please elaborate on how this bug was fixed? The release link contains 55 changed files with 2,875 additions and 3,662 deletions.
> 
> Any hints would be highly appreciated :)

The secret is in the `android` folder. I had to review and change a bunch of files there to make it compatible with the last versions of React Native and Gradle.

**Comment by Vlad-Karlin** [comment]
Thanks for the quick update!

Looking over the fix you've provided - it seems that the bug is solved once the following line is deleted:

`classpath += files(project.getConfigurations().getByName('implementation').asList())` as in the line that caused the build to fail:

> FAILURE: Build failed with an exception.
> 
> Where:
> Build file 'C:\NotificationManager\node_modules\react-native-android-notification-listener\android\build.gradle' line: 106


But still this doesn’t add up - how come a gradle task responsible for a creating a Javadoc, is creating a [variant selection ambiguity error
](https://docs.gradle.org/current/userguide/variant_model.html#sec:variant-select-errors) ?

If you have any inputs on this matter that would be extremely helpful - have been trying to tackle this for a couple of days now..

**Comment by Vlad-Karlin** [comment]
For anyone else that encountered this kind of bug:

I've found another solution that doesn’t require you to delete the failing line in the Javadoc task. By choosing a variant attribute, you can fix the [variant selection ambiguity error](https://docs.gradle.org/current/userguide/variant_model.html#sec:variant-select-errors) - i.e if you want gradle to choose the 

> Variant 'releaseVariantDefaultRuntimePublication'  

then you should let gradle know that the appropriate value for the attribute `com.android.build.api.attributes.BuildTypeAttr` should be `'release'`.

Adding this code in your build.gradle file should do the trick:

`def myAttribute = Attribute.of("com.android.build.api.attributes.BuildTypeAttr", String)

dependencies.attributesSchema {
    // registers this attribute to the attributes schema
    attribute(myAttribute)
}

configurations {
    implementation {
        attributes {
            attribute(myAttribute, "release")
        }
    }
}`
