### ISSUE TITLE
🐞 [BUG] package.json uses react 18.2.0, but latest usable is 18.0.0

### ISSUE THREAD

**Issue by busybox11** [leandrosimoes/react-native-android-notification-listener#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This module's `package.json` uses dep `react@^18.2.0` but the latest version of `react-native` (v0.69.1) uses `react@18.0.0`.
The module installation fails.

### Expected Behavior

The module should be able to install without any dependency error.

### Steps To Reproduce

1. Create a new blank `react-native` v0.69.1 project
2. Try to install the module

### Library version that you are testing

latest (5.0.0)

### Device

Laptop

### Android Version

ArchLinux / Windows 11

### Anything else?

Using `npm` to install the module it fails.
Haven't tried yarn but I'd like to stay with npm.

**Comment by busybox11** [comment]
It does seem to work with yarn but it's much slower and not recommended by React Native's docs using quickstart.
I'm not familiar with it and it's probably fine, but maintaining compatibility with `npm` could be great.

**Comment by leandrosimoes** [comment]
Done: https://github.com/leandrosimoes/react-native-android-notification-listener/releases/tag/v5.0.1
