### ISSUE TITLE
✨ [FEATURE] Module listen when app closed

### ISSUE THREAD

**Issue by khunghang16** [leandrosimoes/react-native-android-notification-listener#48]
### Describe what the feature is about?

Can module listen when app closed?

**Comment by leandrosimoes** [comment]
Hi @khunghang16, yes it should listen when the app is closed.
Please, note that this isn't a feature request or a bug, so it should not have an issue open for this.
In this case, you should open a new topic in the [discussions](https://github.com/leandrosimoes/react-native-android-notification-listener/discussions) page.
