### ISSUE TITLE
🐞 [BUG] Why me can not activate this permissio after generate release apk?

### ISSUE THREAD

**Issue by bagusok** [leandrosimoes/react-native-android-notification-listener#62]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I can't enable notification permission after I generate signed release apk

![Screenshot_20230303-113307_Setelan](https://user-images.githubusercontent.com/52571584/222632522-4ca5101d-9ab2-46f7-9894-42ae92ae82d5.png)
![Screenshot_20230303-113310_Setelan](https://user-images.githubusercontent.com/52571584/222632540-c466c453-031d-49da-af5c-56694986557b.png)

### Expected Behavior

Maybe you have tips for this problem, please help.

### Library version that you are testing

V5.0.1

### Device

Redmi Note 11

### Android Version

13

**Comment by firehand33** [comment]
@bagusok  did u manage to resolve this issue? I have the same issue too...
