### ISSUE TITLE
🐞 [BUG] Cannot handle property requestPermission of null

### ISSUE THREAD

**Issue by MattieTK** [leandrosimoes/react-native-android-notification-listener#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The example app, when run, fails with the following error:

```
 WARN  Possible Unhandled Promise Rejection (id: 2):
TypeError: Cannot read property 'requestPermission' of null
TypeError: Cannot read property 'requestPermission' of null
```

When logged out `RNAndroidNotificationListener` returns null.

### Expected Behavior

The app should run as normal

### Steps To Reproduce

1. Install the example app
2. npm start
3. npm run android
4. Then open the app and observe the errors on the console

### Library version that you are testing

5.0.1

### Device

Emulator Pixel

### Android Version

13

**Comment by LAKSHAYNE** [comment]
Any updates ???

**Comment by mohdhaider07** [comment]
> Any updates ???

did you find any solution?
