### ISSUE TITLE
🐛 [BUG] No task registered for key RNAndroidNotificationListenerHeadlessJs

### ISSUE THREAD

**Issue by aftabaminzoobiapps** [leandrosimoes/react-native-android-notification-listener#8]
Do not listen to the notifications. I have tried the sample in the main repository.  

    list of dependency 

     "moment": "^2.29.1"
     "react": "16.13.1",
     "react-native": "0.63.4",
     "react-native-android-notification-listener": "^2.0.0",
     "react-native-call-detection": "^1.9.0",
     "react-native-device-info": "^7.3.1",
     "react-native-floating-bubble": "^1.0.7",
     "react-native-get-random-values": "^1.5.0",
     "uuid": "^8.3.2"
`      import React, { useState, useEffect } from 'react'
      import { SafeAreaView, Text, Button, AppState,StyleSheet, View } from 'react-native'
      import RNAndroidNotificationListener from 'react-native-android-notification-listener'

      let interval = null

      const App = () => {
          const [hasPermission, setHasPermission] = useState(false)
          const [lastNotification, setLastNotification] = useState(null)

          const handleOnPressPermissionButton = async () => {
              /**
               * Open the notification settings so the user
               * so the user can enable it
               */
              RNAndroidNotificationListener.requestPermission()
          }

          const handleAppStateChange = async nextAppState => {
              if (nextAppState === 'active') {
                  /**
                   * Check the user current notification permission status
                   */
                  RNAndroidNotificationListener.getPermissionStatus().then(status => {
                      setHasPermission(status !== 'denied')
                  })
              }
          }

          const handleCheckNotificationInterval = async () => {

          }

          useEffect(() => {
              AppState.addEventListener('change', handleAppStateChange)

              clearInterval(interval)

              /**
               * Just setting a interval to check if
               * there is a notification in AsyncStorage
               * so I can show it in the application
               */
              interval = setInterval(handleCheckNotificationInterval, 3000)

              return () => {
                  clearInterval(interval)
                  AppState.removeEventListener('change', handleAppStateChange)
              }
          }, [])

          return (
              <SafeAreaView style={styles.container}>
                  <Text style={[styles.permissionStatus, { color: hasPermission ? 'green' : 'red' }]}>
                      {hasPermission
                          ? 'Allowed to handle notifications'
                          : 'NOT allowed to handle notifications'}
                  </Text>
                  <Button
                      title='Open Configuration'
                      onPress={handleOnPressPermissionButton}
                      disabled={hasPermission}
                  />
                  {lastNotification && (
                      <View style={styles.notification}>
                          <Text style={styles.notificationTitle}>Last Notification</Text>
                          <Text>{lastNotification.app}</Text>
                          <Text>{lastNotification.title}</Text>
                          <Text>{lastNotification.text}</Text>
                      </View>
                  )}
              </SafeAreaView>
          )
      }

      export default App
      const styles = StyleSheet.create({
        container: {
          flex: 1,
          justifyContent: 'center',
          alignItems: 'center',
        },
        permissionStatus: {
          marginBottom: 20,
          fontSize: 18,
        },
        notification: {
          width: 300,
          backgroundColor: '#f2f2f2',
          padding: 20,
          marginTop: 20,
          borderRadius: 5,
          elevation: 2,
        },
        notificationTitle: {
          fontWeight: 'bold',
        },
      })
`

index.js

`  
import { AppRegistry } from 'react-native'
import { RNAndroidNotificationListenerHeadlessJsName } from 'react-native-android-notification-listener'

import App from './App'
import { name as appName } from './app.json'

/**
 * Note that this method MUST return a Promise.
 * Is that why I'm using a async function here.
 */
const headlessNotificationListener = notification => {
    if (notification) {
       console.log(notification, 'Notifcation');
    }
}

/**
 * AppRegistry should be required early in the required sequence
 * to make sure the JS execution environment is setup before other
 * modules are required.
 */
AppRegistry.registerHeadlessTask(
    RNAndroidNotificationListenerHeadlessJsName,
    () => headlessNotificationListener
)

AppRegistry.registerComponent(appName, () => App)`

**Comment by leandrosimoes** [comment]
Could you please provide the information below so we can understand better the scenario that you are testing?

**Library version (please complete the following information):**
 - Version [e.g. v2.0.0]

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S10]
 - OS: [e.g. Android 10]

**Additional context**
Add any other context about the problem here.

**Comment by aftabaminzoobiapps** [comment]
> Could you please provide the information below so we can understand better the scenario that you are testing?
> 
> **Library version (please complete the following information):**
> 
> * Version [e.g. v2.0.0]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. Galaxy S10]
> * OS: [e.g. Android 10]
> 
> **Additional context**
> Add any other context about the problem here.

I have tested this on the following previous version which version was working fine but after updating it throw the warning on the following devices.

Device [samsung s2]
OS:[android 8]

Device [Samsung A305F]
OS:[Android 9]
I have made some changes in the library and now it is working fine.

**Comment by leandrosimoes** [comment]
@aftabaminzoobiapps Nice! Could you please provide what you changed to make it works?

**Comment by arunahuja94** [comment]
Facing the same issue, can you please help with the changes

**Comment by leandrosimoes** [comment]
Hi @aftabaminzoobiapps, maybe I figured out what is going on with your code, and maybe is the same issue with your code too  @arunahuja94. Take a look at this part of your code:

```javascript
  /**
  Note that this method MUST return a Promise.
  Is that why I'm using an async function here.
  */
  const headlessNotificationListener = notification => {
      if (notification) {
          console.log(notification, 'Notifcation');
      }
  }
```

Note the comment that is above the `headlessNotificationListener`. It said that this method should return a `Promise`, and that's why I'm using an `async` function in the sample project. Could you please try to use an `async` function or a function that returns a `new Promise(resolve => {})` to see if everything will work fine?

Let me know if this helps, if so, I'll close this issue.

Thanks.

**Comment by aftabaminzoobiapps** [comment]
> Hi @aftabaminzoobiapps, maybe I figured out what is going on with your code, and maybe is the same issue with your code too @arunahuja94. Take a look at this part of your code:
> 
> ```js
>   /**
>   Note that this method MUST return a Promise.
>   Is that why I'm using an async function here.
>   */
>   const headlessNotificationListener = notification => {
>       if (notification) {
>           console.log(notification, 'Notifcation');
>       }
>   }
> ```
> 
> Note the comment that is above the `headlessNotificationListener`. It said that this method should return a `Promise`, and that's why I'm using an `async` function in the sample project. Could you please try to use an `async` function or a function that returns a `new Promise(resolve => {})` to see if everything will work fine?
> 
> Let me know if this helps, if so, I'll close this issue.
> 
> Thanks.

yes, I was the issue. the second thing that I have changed two things in the index.js of the libray to call a function  on the notificationRecieved like this. 
`           import { NativeModules,DeviceEventEmitter } from 'react-native'
           const { RNAndroidNotificationListener } = NativeModules
           const NotificationListener = {}
           export const RNAndroidNotificationListenerHeadlessJsName = 'RNAndroidNotificationListenerHeadlessJs'

           NotificationListener.getPermissionStatus = () => {
              return RNAndroidNotificationListener.getPermissionStatus();
          }
        
          NotificationListener.requestPermission = () => {
              return RNAndroidNotificationListener.requestPermission();
          }

        NotificationListener.onNotificationReceived = callback => {
        // console.log("this is test")
            DeviceEventEmitter.removeAllListeners('notificationReceived');
            return DeviceEventEmitter.addListener('notificationReceived', callback);
        }

        export default NotificationListener;
`
Add these lines to the RNAndroidNotificationListner.java 

` WritableMap params = Arguments.createMap();
                params.putString("app", app);
                params.putString("title", current_incomming_number);
                params.putString("text", current_incomming_number_type);
                RNAndroidNotificationListenerModule.sendEvent("notificationReceived: ", params);`
]
and this functiion to RNAndroidNotifcationListnerModule .java 
`public static void sendEvent(String event, WritableMap params) {
        if (reactContext == null) return;
        reactContext
                .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                .emit(event, params);
    }`



there was no issue with the heraderless task but only i was forgot to create a async function.

**Comment by leandrosimoes** [comment]
Awesome @aftabaminzoobiapps ... thanks for your reply! 
I'll close this issue and take a look at your implementation.

**Comment by arunahuja94** [comment]
working Fine now , thanks @leandrosimoes @aftabaminzoobiapps

**Comment by zoobibackups** [comment]
> working Fine now , thanks @leandrosimoes @aftabaminzoobiapps

welcome @leandrosimoes @arunahuja94
