### ISSUE TITLE
🐛 [BUG]

### ISSUE THREAD

**Issue by arunahuja94** [leandrosimoes/react-native-android-notification-listener#9]
**Describe the bug**
Unable to read each notifications if there is multiple notifications from single app 

**Expected behavior**
Is there a way to listen each notification separately without this group notification message( 2 new messages from 2 chats ) as shown in the screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/78036151/106152355-5b0bde00-61a3-11eb-9a94-7f0d68de7c9e.png)

**Library version (please complete the following information):**
 - Version v2.0.0

**Smartphone (please complete the following information):**
 - Device: Android Emulator (Pixel_api_29)
 - OS: Android 10

**Comment by leandrosimoes** [comment]
Hi, @arunahuja94 I'll do some research to see what can be done in this case and let you know asap. Let me know if you find some info/solution about it.

Thanks

**Comment by arunahuja94** [comment]
**RNAndroidNotificationListener.java** 

import android.text.TextUtils;

 CharSequence[] lines = notification.extras.getCharSequenceArray(Notification.EXTRA_TEXT_LINES);
 CharSequence chars = notification.extras.getCharSequence(Notification.EXTRA_BIG_TEXT);	

 `if(lines != null && lines.length > 0) {
      StringBuilder sb = new StringBuilder();
   for (CharSequence msg : lines)
      if (!TextUtils.isEmpty(msg)) {
         sb.append(msg.toString());
         sb.append('\n');
      }
   String allBundlednotif = sb.toString().trim();
   serviceIntent.putExtra("allBundlednotif", allBundlednotif);
}`

**this for extra large text** 
   ` if(!TextUtils.isEmpty(chars))
           {
            String alltext = chars.toString();
	    serviceIntent.putExtra("alltext", alltext);
            }`


Please check these changes, as in **allBundlednotif**  i am able to get all the bundled notifications as string,  but i need to retrieve the new ones only and in an array , could you please take a look and help me with that   @leandrosimoes

**Comment by leandrosimoes** [comment]
Hi @arunahuja94, thanks for your answer. 

I already implemented the logic to get the big text and the grouped messages based on your code and seems to be working just fine, I'll just make more tests today and publish a new version asap.

**Comment by arunahuja94** [comment]
Hi @leandrosimoes.

Implemented your changes , Is it Possible to get each notifications from group messages separately or with some notification id , So that I could remove the duplicates that I receive from single notification and grouped notification.

getting each notification from group messages separately can also help with removing duplicates if not with notification id

Can you Please help me with this, thanks

**Comment by leandrosimoes** [comment]
Hi @arunahuja94! I'll take a look at this later and let you know. Thanks.

**Comment by leandrosimoes** [comment]
Hi, @arunahuja94 I just released version 3.0.0 of this package with the changes. Note that I changed the payload of the whole payload of the notification to be a JSON string, so before you use the notification you must `JSON.parse`. You can see more [here](https://github.com/leandrosimoes/react-native-android-notification-listener#usage).

Thanks for the help!
